# theme: jeffreytse/jekyll-theme-yat
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"